### ISSUE TITLE
No Error on 429 response from OpenAI API

### ISSUE THREAD

**Issue by sambarnes90** [thomasuebi/academia-os#1]
Just a quick UX thing really.

Had to open Devtools to see that the responses weren't streaming because of a rate limit on the OpenAI API (429 response from request to https://api.openai.com/v1/chat/completions).

Might be worth having something user facing that alerts this fact?

**Comment by thomasuebi** [comment]
Agreed, will implement more concrete user-facing error messages. Thanks for raising this issue.

**Comment by thomasuebi** [comment]
Support for better user-facing error messages is implemented
